### ISSUE TITLE
kore fails to build with clang 3.9 on FreeBSD

### ISSUE THREAD

**Issue by t6** [jorisvink/kore#153]
FreeBSD is in the process of upgrading to clang 3.9 and building kore with it fails (see [1]): 
```
src/pgsql.c:222:17: error: passing an object that undergoes default argument promotion to 'va_start'
      has undefined behavior [-Werror,-Wvarargs]
        va_start(args, count);
                       ^
src/pgsql.c:217:45: note: parameter of type 'u_int8_t' (aka 'unsigned char') is declared here
    const char *query, int result, u_int8_t count, ...)
```
More information about this warning can be found on [2].

To solve this I can change the type of `count` to `int` in `kore_pgsql_query_params()` and `kore_pgsql_v_query_params()`. This also matches the signatures of both `PQexecParams()` [3] and `PQsendQueryParams()` [4].  I don't see why `count` has to be an `u_int8_t`.

I'll open a pull request if you think this is ok to do.

[1] https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=214639
[2] https://www.securecoding.cert.org/confluence/display/cplusplus/EXP58-CPP.+Pass+an+object+of+the+correct+type+to+va_start
[3] https://www.postgresql.org/docs/9.2/static/libpq-exec.html
[4] https://www.postgresql.org/docs/9.2/static/libpq-async.html

**Comment by jorisvink** [comment]
Excellent catch. Please do make a PR asap.
