### ISSUE TITLE
PostgreSQL support fails to build on FreeBSD 10.3/i386

### ISSUE THREAD

**Issue by t6** [jorisvink/kore#144]
I'm trying to create a FreeBSD port of kore: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=211603. We are currently seeing build failures related to PostgreSQL support on FreeBSD 10.2 and 10.3/i386. Interestingly this does not happen on FreeBSD/amd64.
```
cc -O2 -pipe  -fstack-protector -fno-strict-aliasing -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Iincludes -std=c99 -pedantic -DPREFIX='"/usr/local"' -I/usr/local/include -DKORE_USE_PGSQL -DPGSQL_INCLUDE_PATH="\"/usr/local/include\"" -DKORE_USE_TASKS -DKORE_USE_JSONRPC -I/usr/local/include -c src/pgsql.c -o obj/pgsql.o
src/pgsql.c:222:6: error: variable 'args' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
        if (count > 0)
            ^~~~~~~~~
src/pgsql.c:225:63: note: uninitialized use occurs here
        ret = kore_pgsql_v_query_params(pgsql, query, result, count, args);
                                                                     ^~~~
src/pgsql.c:222:2: note: remove the 'if' if its condition is always true
        if (count > 0)
        ^~~~~~~~~~~~~~
src/pgsql.c:220:15: note: initialize the variable 'args' to silence this warning
        va_list         args;
                            ^
                             = NULL
1 error generated.
gmake[1]: *** [Makefile:106: obj/pgsql.o] Error 1
```
The full build log is here: https://people.freebsd.org/~pi/logs/devel__kore-10i-1472321629.txt. Do you think it's safe to ignore this warning? Do we need the `if (count > 0)` check in `kore_pgsql_query_params`?

**Comment by jorisvink** [comment]
Hi,

I can't look at this problem just yet as I'm still on vacation, but I'll get back to this when I get back!

.joris

**Comment by jorisvink** [comment]
FYI, yes the va_start and va_end should always be called regardless of count. I can't make that change yet tho but a PR would be neat :)

**Comment by t6** [comment]
> I can't make that change yet tho but a PR would be neat :)

Of course, see #146
