### ISSUE TITLE
Couldn't build in OSX 10.11 missing openssl

### ISSUE THREAD

**Issue by guoxiao** [jorisvink/kore#70]
I've installed `openssl` in homebrew, but the build still fails.

```
% kore build                                                                                                                                              :(
compiling koredemo.c
In file included from ./src/koredemo.c:1:
/usr/local/Cellar/kore/1.2.3/include/kore/kore.h:30:10: fatal error: 'openssl/err.h' file not found
#include <openssl/err.h>
         ^
1 error generated.
kore build: subprocess trouble, check output
```

And I tried to add env before build, run `CFLAGS="-I/usr/local/opt/openssl/include" kore build` and it still fails. But the file `/usr/local/opt/openssl/include/openssl/err.h` exists.

**Comment by jorisvink** [comment]
I unfortunately cannot reproduce this.

Did you install kore from homebrew or built it from scratch? The CFLAGS directive wasn't being honored until recently so 1.2.3 (in homebrew) does not allow you to do this.

I suggest cloning the latest code, build and install it and retry compiling it again so that your CFLAGS are picked up. Let me know how that works out.

**Comment by guoxiao** [comment]
> Did you install kore from homebrew or built it from scratch?
I installed kore from homebrew. The version is 1.2.3.

> I suggest cloning the latest code, build and install it and retry compiling it again so that your CFLAGS are picked up. Let me know how that works out.
I reinstalled kore with `brew kore --HEAD` and it works out.

Maybe I need to submit a patch to homebrew to include -I/usr/local/opt/openssl/include in the default CFLAGS.

**Comment by guoxiao** [comment]
I find in the `Makefile`, `-I/usr/local/opt/openssl/include` is already included in the CFLAGS. Can we have it default in the `kore build` too?

**Comment by jorisvink** [comment]
Did you link openssl via brew btw?

$ brew link openssl

So that it gets linked under /usr/local/include (which kore build includes).

**Comment by guoxiao** [comment]
It's not recommended to link openssl.
```
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include
```

**Comment by jorisvink** [comment]
Right'o.

I'll considering adding this as a default include path for OSX.

**Comment by jorisvink** [comment]
Added default openssl paths for homebrew/ports to the cli build now.

**Comment by guoxiao** [comment]
We may also need adding `-L/usr/local/opt/openssl/lib` to `LDFLAGS`, or we will use brewed openssl headers but link against OSX's openssl library.

**Comment by jorisvink** [comment]
That is not needed when building the shared libs.

**Comment by guoxiao** [comment]
That's good.
Once we have a new release including this patch, I will submit it to homebrew.

**Comment by jorisvink** [comment]
Closing this issue as the problem is relates to is resolved.
